version: '2'

services:
    postgres: 
        image: postgres:9.4.7
        ports:
            - '5432:5432'
        environment:
            POSTGRES_USER: 'postgres'
            POSTGRES_PASSWORD: 'postgres'
            POSTGRES_DB: 'messages'
