version: '2'
services:
    jsonserver:
        build: 'mock-services'
        ports:
            - 3001:3001
    postgres:
        image: postgres:9.5
        ports:
            - '5432:5432'
        environment:
            POSTGRES_USER: 'coder'
            POSTGRES_PASSWORD: 'mysecretpassword'
            POSTGRES_DB: 'messages'
