branch-defaults:
  dev:
    environment: tc-message-api-v4-dev
    group_suffix: null
  master:
    environment: tc-message-api-v4-prod
    group_suffix: null
global:
  application_name: tc-message-service
  default_ec2_keyname: topcoder-dev-vpc-app
  default_platform: Docker 1.11.2
  default_region: us-east-1
  profile: null
  sc: git
